# Generated by Django 5.1.6 on 2025-02-12 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light Activity'), ('moderate', 'Moderate Activity'), ('active', 'Active'), ('very_active', 'Very Active')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='workout_preference',
            field=models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('yoga', 'Yoga'), ('crossfit', 'CrossFit'), ('mixed', 'Mixed Workouts')], default='mixed', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
