# Generated by Django 4.2 on 2025-03-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_healthdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
